-- Generated. Updates local_governments.geo_code from southkorea-maps kostat 2018.
-- Multiple LG rows may share the same geo_code (e.g. 부천시 일반구).
-- Manual overrides for post-2018 admin reorganizations:
--   인천 미추홀구  ← 2018-07 renamed from "인천광역시 남구" (geo polygon 23030)
--   대구 군위군    ← 2023-07 transferred from 경상북도 to 대구광역시 (geo polygon 37310)
begin;
update public.local_governments set geo_code='23030' where full_name='인천광역시 미추홀구';
update public.local_governments set geo_code='37310' where full_name='대구광역시 군위군';
update public.local_governments set geo_code='11010' where full_name='서울특별시 종로구';
update public.local_governments set geo_code='11020' where full_name='서울특별시 중구';
update public.local_governments set geo_code='11030' where full_name='서울특별시 용산구';
update public.local_governments set geo_code='11040' where full_name='서울특별시 성동구';
update public.local_governments set geo_code='11050' where full_name='서울특별시 광진구';
update public.local_governments set geo_code='11060' where full_name='서울특별시 동대문구';
update public.local_governments set geo_code='11070' where full_name='서울특별시 중랑구';
update public.local_governments set geo_code='11080' where full_name='서울특별시 성북구';
update public.local_governments set geo_code='11090' where full_name='서울특별시 강북구';
update public.local_governments set geo_code='11100' where full_name='서울특별시 도봉구';
update public.local_governments set geo_code='11110' where full_name='서울특별시 노원구';
update public.local_governments set geo_code='11120' where full_name='서울특별시 은평구';
update public.local_governments set geo_code='11130' where full_name='서울특별시 서대문구';
update public.local_governments set geo_code='11140' where full_name='서울특별시 마포구';
update public.local_governments set geo_code='11150' where full_name='서울특별시 양천구';
update public.local_governments set geo_code='11160' where full_name='서울특별시 강서구';
update public.local_governments set geo_code='11170' where full_name='서울특별시 구로구';
update public.local_governments set geo_code='11180' where full_name='서울특별시 금천구';
update public.local_governments set geo_code='11190' where full_name='서울특별시 영등포구';
update public.local_governments set geo_code='11200' where full_name='서울특별시 동작구';
update public.local_governments set geo_code='11210' where full_name='서울특별시 관악구';
update public.local_governments set geo_code='11220' where full_name='서울특별시 서초구';
update public.local_governments set geo_code='11230' where full_name='서울특별시 강남구';
update public.local_governments set geo_code='11240' where full_name='서울특별시 송파구';
update public.local_governments set geo_code='11250' where full_name='서울특별시 강동구';
update public.local_governments set geo_code='24010' where full_name='광주광역시 동구';
update public.local_governments set geo_code='24020' where full_name='광주광역시 서구';
update public.local_governments set geo_code='24030' where full_name='광주광역시 남구';
update public.local_governments set geo_code='24040' where full_name='광주광역시 북구';
update public.local_governments set geo_code='24050' where full_name='광주광역시 광산구';
update public.local_governments set geo_code='22010' where full_name='대구광역시 중구';
update public.local_governments set geo_code='22020' where full_name='대구광역시 동구';
update public.local_governments set geo_code='22030' where full_name='대구광역시 서구';
update public.local_governments set geo_code='22040' where full_name='대구광역시 남구';
update public.local_governments set geo_code='22050' where full_name='대구광역시 북구';
update public.local_governments set geo_code='22060' where full_name='대구광역시 수성구';
update public.local_governments set geo_code='22070' where full_name='대구광역시 달서구';
update public.local_governments set geo_code='22310' where full_name='대구광역시 달성군';
update public.local_governments set geo_code='25010' where full_name='대전광역시 동구';
update public.local_governments set geo_code='25020' where full_name='대전광역시 중구';
update public.local_governments set geo_code='25030' where full_name='대전광역시 서구';
update public.local_governments set geo_code='25040' where full_name='대전광역시 유성구';
update public.local_governments set geo_code='25050' where full_name='대전광역시 대덕구';
update public.local_governments set geo_code='21010' where full_name='부산광역시 중구';
update public.local_governments set geo_code='21020' where full_name='부산광역시 서구';
update public.local_governments set geo_code='21030' where full_name='부산광역시 동구';
update public.local_governments set geo_code='21040' where full_name='부산광역시 영도구';
update public.local_governments set geo_code='21050' where full_name='부산광역시 부산진구';
update public.local_governments set geo_code='21060' where full_name='부산광역시 동래구';
update public.local_governments set geo_code='21070' where full_name='부산광역시 남구';
update public.local_governments set geo_code='21080' where full_name='부산광역시 북구';
update public.local_governments set geo_code='21090' where full_name='부산광역시 해운대구';
update public.local_governments set geo_code='21100' where full_name='부산광역시 사하구';
update public.local_governments set geo_code='21110' where full_name='부산광역시 금정구';
update public.local_governments set geo_code='21120' where full_name='부산광역시 강서구';
update public.local_governments set geo_code='21130' where full_name='부산광역시 연제구';
update public.local_governments set geo_code='21140' where full_name='부산광역시 수영구';
update public.local_governments set geo_code='21150' where full_name='부산광역시 사상구';
update public.local_governments set geo_code='21310' where full_name='부산광역시 기장군';
update public.local_governments set geo_code='26010' where full_name='울산광역시 중구';
update public.local_governments set geo_code='26020' where full_name='울산광역시 남구';
update public.local_governments set geo_code='26030' where full_name='울산광역시 동구';
update public.local_governments set geo_code='26040' where full_name='울산광역시 북구';
update public.local_governments set geo_code='26310' where full_name='울산광역시 울주군';
update public.local_governments set geo_code='23010' where full_name='인천광역시 중구';
update public.local_governments set geo_code='23020' where full_name='인천광역시 동구';
update public.local_governments set geo_code='23040' where full_name='인천광역시 연수구';
update public.local_governments set geo_code='23050' where full_name='인천광역시 남동구';
update public.local_governments set geo_code='23060' where full_name='인천광역시 부평구';
update public.local_governments set geo_code='23070' where full_name='인천광역시 계양구';
update public.local_governments set geo_code='23080' where full_name='인천광역시 서구';
update public.local_governments set geo_code='23310' where full_name='인천광역시 강화군';
update public.local_governments set geo_code='23320' where full_name='인천광역시 옹진군';
update public.local_governments set geo_code='29010' where full_name='세종특별자치시';
update public.local_governments set geo_code='31011' where full_name='경기도 수원시 장안구';
update public.local_governments set geo_code='31012' where full_name='경기도 수원시 권선구';
update public.local_governments set geo_code='31013' where full_name='경기도 수원시 팔달구';
update public.local_governments set geo_code='31014' where full_name='경기도 수원시 영통구';
update public.local_governments set geo_code='31021' where full_name='경기도 성남시 수정구';
update public.local_governments set geo_code='31022' where full_name='경기도 성남시 중원구';
update public.local_governments set geo_code='31023' where full_name='경기도 성남시 분당구';
update public.local_governments set geo_code='31101' where full_name='경기도 고양시 덕양구';
update public.local_governments set geo_code='31103' where full_name='경기도 고양시 일산동구';
update public.local_governments set geo_code='31104' where full_name='경기도 고양시 일산서구';
update public.local_governments set geo_code='31191' where full_name='경기도 용인시 처인구';
update public.local_governments set geo_code='31192' where full_name='경기도 용인시 기흥구';
update public.local_governments set geo_code='31193' where full_name='경기도 용인시 수지구';
update public.local_governments set geo_code='31050' where full_name='경기도 부천시 원미구';
update public.local_governments set geo_code='31050' where full_name='경기도 부천시 소사구';
update public.local_governments set geo_code='31050' where full_name='경기도 부천시 오정구';
update public.local_governments set geo_code='31091' where full_name='경기도 안산시 상록구';
update public.local_governments set geo_code='31092' where full_name='경기도 안산시 단원구';
update public.local_governments set geo_code='31041' where full_name='경기도 안양시 만안구';
update public.local_governments set geo_code='31042' where full_name='경기도 안양시 동안구';
update public.local_governments set geo_code='31130' where full_name='경기도 남양주시';
update public.local_governments set geo_code='31240' where full_name='경기도 화성시';
update public.local_governments set geo_code='31070' where full_name='경기도 평택시';
update public.local_governments set geo_code='31030' where full_name='경기도 의정부시';
update public.local_governments set geo_code='31150' where full_name='경기도 시흥시';
update public.local_governments set geo_code='31200' where full_name='경기도 파주시';
update public.local_governments set geo_code='31230' where full_name='경기도 김포시';
update public.local_governments set geo_code='31060' where full_name='경기도 광명시';
update public.local_governments set geo_code='31250' where full_name='경기도 광주시';
update public.local_governments set geo_code='31160' where full_name='경기도 군포시';
update public.local_governments set geo_code='31140' where full_name='경기도 오산시';
update public.local_governments set geo_code='31210' where full_name='경기도 이천시';
update public.local_governments set geo_code='31260' where full_name='경기도 양주시';
update public.local_governments set geo_code='31220' where full_name='경기도 안성시';
update public.local_governments set geo_code='31120' where full_name='경기도 구리시';
update public.local_governments set geo_code='31270' where full_name='경기도 포천시';
update public.local_governments set geo_code='31170' where full_name='경기도 의왕시';
update public.local_governments set geo_code='31180' where full_name='경기도 하남시';
update public.local_governments set geo_code='31280' where full_name='경기도 여주시';
update public.local_governments set geo_code='31080' where full_name='경기도 동두천시';
update public.local_governments set geo_code='31110' where full_name='경기도 과천시';
update public.local_governments set geo_code='31350' where full_name='경기도 연천군';
update public.local_governments set geo_code='31370' where full_name='경기도 가평군';
update public.local_governments set geo_code='31380' where full_name='경기도 양평군';
update public.local_governments set geo_code='38111' where full_name='경상남도 창원시 의창구';
update public.local_governments set geo_code='38112' where full_name='경상남도 창원시 성산구';
update public.local_governments set geo_code='38113' where full_name='경상남도 창원시 마산합포구';
update public.local_governments set geo_code='38114' where full_name='경상남도 창원시 마산회원구';
update public.local_governments set geo_code='38115' where full_name='경상남도 창원시 진해구';
update public.local_governments set geo_code='38030' where full_name='경상남도 진주시';
update public.local_governments set geo_code='38050' where full_name='경상남도 통영시';
update public.local_governments set geo_code='38060' where full_name='경상남도 사천시';
update public.local_governments set geo_code='38070' where full_name='경상남도 김해시';
update public.local_governments set geo_code='38080' where full_name='경상남도 밀양시';
update public.local_governments set geo_code='38090' where full_name='경상남도 거제시';
update public.local_governments set geo_code='38100' where full_name='경상남도 양산시';
update public.local_governments set geo_code='38310' where full_name='경상남도 의령군';
update public.local_governments set geo_code='38320' where full_name='경상남도 함안군';
update public.local_governments set geo_code='38330' where full_name='경상남도 창녕군';
update public.local_governments set geo_code='38340' where full_name='경상남도 고성군';
update public.local_governments set geo_code='38350' where full_name='경상남도 남해군';
update public.local_governments set geo_code='38360' where full_name='경상남도 하동군';
update public.local_governments set geo_code='38370' where full_name='경상남도 산청군';
update public.local_governments set geo_code='38380' where full_name='경상남도 함양군';
update public.local_governments set geo_code='38390' where full_name='경상남도 거창군';
update public.local_governments set geo_code='38400' where full_name='경상남도 합천군';
update public.local_governments set geo_code='37011' where full_name='경상북도 포항시 남구';
update public.local_governments set geo_code='37012' where full_name='경상북도 포항시 북구';
update public.local_governments set geo_code='37020' where full_name='경상북도 경주시';
update public.local_governments set geo_code='37030' where full_name='경상북도 김천시';
update public.local_governments set geo_code='37040' where full_name='경상북도 안동시';
update public.local_governments set geo_code='37050' where full_name='경상북도 구미시';
update public.local_governments set geo_code='37060' where full_name='경상북도 영주시';
update public.local_governments set geo_code='37070' where full_name='경상북도 영천시';
update public.local_governments set geo_code='37080' where full_name='경상북도 상주시';
update public.local_governments set geo_code='37090' where full_name='경상북도 문경시';
update public.local_governments set geo_code='37100' where full_name='경상북도 경산시';
update public.local_governments set geo_code='37320' where full_name='경상북도 의성군';
update public.local_governments set geo_code='37330' where full_name='경상북도 청송군';
update public.local_governments set geo_code='37340' where full_name='경상북도 영양군';
update public.local_governments set geo_code='37350' where full_name='경상북도 영덕군';
update public.local_governments set geo_code='37360' where full_name='경상북도 청도군';
update public.local_governments set geo_code='37370' where full_name='경상북도 고령군';
update public.local_governments set geo_code='37380' where full_name='경상북도 성주군';
update public.local_governments set geo_code='37390' where full_name='경상북도 칠곡군';
update public.local_governments set geo_code='37400' where full_name='경상북도 예천군';
update public.local_governments set geo_code='37410' where full_name='경상북도 봉화군';
update public.local_governments set geo_code='37420' where full_name='경상북도 울진군';
update public.local_governments set geo_code='37430' where full_name='경상북도 울릉군';
update public.local_governments set geo_code='36010' where full_name='전라남도 목포시';
update public.local_governments set geo_code='36020' where full_name='전라남도 여수시';
update public.local_governments set geo_code='36030' where full_name='전라남도 순천시';
update public.local_governments set geo_code='36040' where full_name='전라남도 나주시';
update public.local_governments set geo_code='36060' where full_name='전라남도 광양시';
update public.local_governments set geo_code='36310' where full_name='전라남도 담양군';
update public.local_governments set geo_code='36320' where full_name='전라남도 곡성군';
update public.local_governments set geo_code='36330' where full_name='전라남도 구례군';
update public.local_governments set geo_code='36350' where full_name='전라남도 고흥군';
update public.local_governments set geo_code='36360' where full_name='전라남도 보성군';
update public.local_governments set geo_code='36370' where full_name='전라남도 화순군';
update public.local_governments set geo_code='36380' where full_name='전라남도 장흥군';
update public.local_governments set geo_code='36390' where full_name='전라남도 강진군';
update public.local_governments set geo_code='36400' where full_name='전라남도 해남군';
update public.local_governments set geo_code='36410' where full_name='전라남도 영암군';
update public.local_governments set geo_code='36420' where full_name='전라남도 무안군';
update public.local_governments set geo_code='36430' where full_name='전라남도 함평군';
update public.local_governments set geo_code='36440' where full_name='전라남도 영광군';
update public.local_governments set geo_code='36450' where full_name='전라남도 장성군';
update public.local_governments set geo_code='36460' where full_name='전라남도 완도군';
update public.local_governments set geo_code='36470' where full_name='전라남도 진도군';
update public.local_governments set geo_code='36480' where full_name='전라남도 신안군';
update public.local_governments set geo_code='34011' where full_name='충청남도 천안시 동남구';
update public.local_governments set geo_code='34012' where full_name='충청남도 천안시 서북구';
update public.local_governments set geo_code='34020' where full_name='충청남도 공주시';
update public.local_governments set geo_code='34030' where full_name='충청남도 보령시';
update public.local_governments set geo_code='34040' where full_name='충청남도 아산시';
update public.local_governments set geo_code='34050' where full_name='충청남도 서산시';
update public.local_governments set geo_code='34060' where full_name='충청남도 논산시';
update public.local_governments set geo_code='34070' where full_name='충청남도 계룡시';
update public.local_governments set geo_code='34080' where full_name='충청남도 당진시';
update public.local_governments set geo_code='34310' where full_name='충청남도 금산군';
update public.local_governments set geo_code='34330' where full_name='충청남도 부여군';
update public.local_governments set geo_code='34340' where full_name='충청남도 서천군';
update public.local_governments set geo_code='34350' where full_name='충청남도 청양군';
update public.local_governments set geo_code='34360' where full_name='충청남도 홍성군';
update public.local_governments set geo_code='34370' where full_name='충청남도 예산군';
update public.local_governments set geo_code='34380' where full_name='충청남도 태안군';
update public.local_governments set geo_code='33041' where full_name='충청북도 청주시 상당구';
update public.local_governments set geo_code='33042' where full_name='충청북도 청주시 서원구';
update public.local_governments set geo_code='33043' where full_name='충청북도 청주시 흥덕구';
update public.local_governments set geo_code='33044' where full_name='충청북도 청주시 청원구';
update public.local_governments set geo_code='33020' where full_name='충청북도 충주시';
update public.local_governments set geo_code='33030' where full_name='충청북도 제천시';
update public.local_governments set geo_code='33320' where full_name='충청북도 보은군';
update public.local_governments set geo_code='33330' where full_name='충청북도 옥천군';
update public.local_governments set geo_code='33340' where full_name='충청북도 영동군';
update public.local_governments set geo_code='33390' where full_name='충청북도 증평군';
update public.local_governments set geo_code='33350' where full_name='충청북도 진천군';
update public.local_governments set geo_code='33360' where full_name='충청북도 괴산군';
update public.local_governments set geo_code='33370' where full_name='충청북도 음성군';
update public.local_governments set geo_code='33380' where full_name='충청북도 단양군';
update public.local_governments set geo_code='32010' where full_name='강원특별자치도 춘천시';
update public.local_governments set geo_code='32020' where full_name='강원특별자치도 원주시';
update public.local_governments set geo_code='32030' where full_name='강원특별자치도 강릉시';
update public.local_governments set geo_code='32040' where full_name='강원특별자치도 동해시';
update public.local_governments set geo_code='32050' where full_name='강원특별자치도 태백시';
update public.local_governments set geo_code='32060' where full_name='강원특별자치도 속초시';
update public.local_governments set geo_code='32070' where full_name='강원특별자치도 삼척시';
update public.local_governments set geo_code='32310' where full_name='강원특별자치도 홍천군';
update public.local_governments set geo_code='32320' where full_name='강원특별자치도 횡성군';
update public.local_governments set geo_code='32330' where full_name='강원특별자치도 영월군';
update public.local_governments set geo_code='32340' where full_name='강원특별자치도 평창군';
update public.local_governments set geo_code='32350' where full_name='강원특별자치도 정선군';
update public.local_governments set geo_code='32360' where full_name='강원특별자치도 철원군';
update public.local_governments set geo_code='32370' where full_name='강원특별자치도 화천군';
update public.local_governments set geo_code='32380' where full_name='강원특별자치도 양구군';
update public.local_governments set geo_code='32390' where full_name='강원특별자치도 인제군';
update public.local_governments set geo_code='32400' where full_name='강원특별자치도 고성군';
update public.local_governments set geo_code='32410' where full_name='강원특별자치도 양양군';
update public.local_governments set geo_code='35011' where full_name='전북특별자치도 전주시 완산구';
update public.local_governments set geo_code='35012' where full_name='전북특별자치도 전주시 덕진구';
update public.local_governments set geo_code='35020' where full_name='전북특별자치도 군산시';
update public.local_governments set geo_code='35030' where full_name='전북특별자치도 익산시';
update public.local_governments set geo_code='35040' where full_name='전북특별자치도 정읍시';
update public.local_governments set geo_code='35050' where full_name='전북특별자치도 남원시';
update public.local_governments set geo_code='35060' where full_name='전북특별자치도 김제시';
update public.local_governments set geo_code='35310' where full_name='전북특별자치도 완주군';
update public.local_governments set geo_code='35320' where full_name='전북특별자치도 진안군';
update public.local_governments set geo_code='35330' where full_name='전북특별자치도 무주군';
update public.local_governments set geo_code='35340' where full_name='전북특별자치도 장수군';
update public.local_governments set geo_code='35350' where full_name='전북특별자치도 임실군';
update public.local_governments set geo_code='35360' where full_name='전북특별자치도 순창군';
update public.local_governments set geo_code='35370' where full_name='전북특별자치도 고창군';
update public.local_governments set geo_code='35380' where full_name='전북특별자치도 부안군';
update public.local_governments set geo_code='39010' where full_name='제주특별자치도 제주시';
update public.local_governments set geo_code='39020' where full_name='제주특별자치도 서귀포시';
commit;

